"""Dashboard: status at a glance, quick actions, recent work and setup guidance."""

from __future__ import annotations

import streamlit as st

from studio.services import health
from studio.storage import repository as repo

from .. import state
from ..compat import FULL
from ..components import (
    badge,
    badges,
    banner,
    check_rows,
    empty_state,
    html,
    list_row,
    page_header,
    panel,
    section,
    stat_tiles,
)
from ..formatting import fmt_duration_words, fmt_size, fmt_when, greeting

_TONE = {"done": "success", "failed": "danger", "cancelled": "neutral", "interrupted": "warning", "running": "accent"}
_LABEL = {"done": "Completed", "failed": "Failed", "cancelled": "Cancelled", "interrupted": "Interrupted", "running": "Running"}


def render() -> None:
    page_header(greeting(), "Your private speech workspace. Nothing here ever leaves this computer.", eyebrow="Offline Voice Studio", icon_name="sparkle")

    checks = health.run_checks()
    ready = health.speech_ready()
    required_ok = all(c.ok for c in checks if c.required)

    html(
        '<section class="vs-hero"><h2>Turn any text into natural speech</h2>'
        "<p>Paste text or import a PDF, Word, TXT or Markdown file, pick a voice, preview it, and export WAV or MP3. "
        "Speech is generated by an offline neural engine on your own hardware.</p>"
        + badges(
            [
                badge("100% offline", "success", "shield"),
                badge("Speech engine ready" if ready else "Setup needed", "success" if ready else "warning", "cpu"),
                badge("Local SQLite storage", "neutral", "database"),
            ]
        )
        + "</section>"
    )

    a, b, c, d = st.columns(4)
    a.button("New speech", key="dash_tts", on_click=state.go, args=("tts",), type="primary", **FULL, icon=":material/graphic_eq:")
    b.button("Import a document", key="dash_doc", on_click=state.go, args=("documents",), **FULL, icon=":material/upload_file:")
    c.button("Create a voice", key="dash_voice", on_click=state.go, args=("voice",), **FULL, icon=":material/mic:")
    d.button("Audio Library", key="dash_lib", on_click=state.go, args=("library",), **FULL, icon=":material/library_music:")

    stats = repo.stats()
    section("Overview", "dashboard")
    stat_tiles(
        [
            ("zap", "Generations", f"{stats['generations']:,}", f"{stats['failed']:,} failed" if stats["failed"] else "All successful"),
            ("headphones", "Audio created", fmt_duration_words(stats["audio_seconds"]) if stats["audio_seconds"] else "0 s", f"{stats['audio_files']:,} files"),
            ("database", "Storage used", fmt_size(stats["storage_bytes"]), "Audio library"),
            ("mic", "Custom voices", f"{stats['voices']:,}", "Reference profiles"),
            ("document", "Documents", f"{stats['documents']:,}", "Saved texts"),
        ]
    )

    left, right = st.columns([1.5, 1], gap="large")
    with left:
        section("Recent activity", "history")
        with panel("dash-recent"):
            recent = repo.list_history(limit=6)
            if not recent:
                empty_state("tts", "Nothing generated yet", "Your first conversion will show up here with its voice, length and status.")
            else:
                rows = "".join(
                    list_row(
                        r["title"],
                        f"{r['voice_label'] or 'No voice'}  ·  {r['char_count'] or 0:,} characters",
                        fmt_when(r["created_at"]),
                        badge(_LABEL.get(r["status"], r["status"]), _TONE.get(r["status"], "neutral")),
                    )
                    for r in recent
                )
                html(f"<div>{rows}</div>")
                st.button("View full history", key="dash_hist", on_click=state.go, args=("history",), type="tertiary", icon=":material/arrow_forward:")
    with right:
        section("Setup status", "cpu")
        with panel("dash-health"):
            if required_ok:
                banner("success", "Everything required is installed", "Optional items below add MP3 export, more import formats and cloning.")
            else:
                banner("warning", "A few things need attention", "Follow the hint under each item, then restart the app.")
            check_rows([(c.ok, c.label, c.detail) for c in checks])
